version: '2'
services:
    taxi24api-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/taxi24api/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=taxi24api
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
